# Generated by Django 4.1.5 on 2023-05-07 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Yetenek Adı')),
                ('statu', models.IntegerField(default=0, verbose_name='Yetenek Değeri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50, verbose_name='Şifre')),
                ('job', models.CharField(default='-', max_length=50, verbose_name='İş')),
                ('image', models.FileField(default='None/download.jpg', upload_to=None, verbose_name='Fotoğraf')),
                ('phone', models.CharField(default='-', max_length=50, verbose_name='Telefon Numarası')),
                ('adress', models.CharField(default='-', max_length=50, verbose_name='Adres')),
                ('status', models.ManyToManyField(to='quiz.userinfostatus', verbose_name='Yetenekler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(max_length=500, verbose_name='İçerik')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('post_url', models.URLField(verbose_name='Url Adresi')),
                ('image1', models.FileField(upload_to='', verbose_name='Fotoğraf 1')),
                ('image2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 2')),
                ('image3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf 3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category', verbose_name='Kategori')),
            ],
        ),
    ]
